services:
  translateany:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app/Config:/var/www/html/app/Config
    restart: always
